### ISSUE TITLE
libcvextern.so not in /usr/lib/vignette after install

### ISSUE THREAD

**Issue by Amberarch** [vignetteapp/aur-vignette-git#1]
libcvextern.so Is not present in /usr/lib/vignette/ after running makepkg. I was able to make the program run, but only after copying `$HOME/.nugget/packages/emgu.cv.runtime.ubuntu.20.04-x64/4.5.3.4721/runtimes/ubuntu.20.04-x64/native/libcvextern.so` to `/usr/lib/vignette/`

**Comment by iojcde** [comment]
I'm pretty sure this is a known issue. 
cc @Speykious?

**Comment by Speykious** [comment]
Kind of. When you build Vignette for yourself with `dotnet build` under Linux, the EmguCV runtime gets put under the `runtimes/ubuntu.20.04-x64/native/` subfolder of the build directory, no matter the distribution. I reported that specific bug [here](https://github.com/emgucv/emgucv/issues/617).

For the AUR package though, the issue is slightly different: when Vignette is built with `dotnet publish`, the runtime is actually nowhere to be found even though the dependency is there in the `.csproj`. And I don't know why this happens.

**Comment by Speykious** [comment]
Welp... Issue fixed. I was using the wrong argument for the `--runtime` option this entire time.
